travis:
  secure:
    BINSTAR_TOKEN: mU6pR5pyIpExIpJUtL8rDE66cID26k9QMQ7ZST4HUBgUCk8+99uMcs7Ic3JY+BN6ar1firpQM90oR4IFo8Mit7+0mx0NigDQH+30ndF6Vol8V2mqUEkhawvU3egs+RKJsgcv95ueg0Ta0K9M/3lDyF1cIGRGhZ1g/ppQGadWzqUNYmdNHQCnSYPuQ8QVDn9nRWpl+78YbuGLLNNazver9DiL+lPKDj+yOtia9rtD70d90U9/QWFEaTw01FOBd2iIlHoMpXMHro7NiTwLo2e18gOCBcg2f9KC/GCvUNuMaiurVzbLr1uIz1/G1/FgWwkqofIz3WhtzNLYFlqIb/uQJCj6EsEnvrl8OgGaJRO64niFBbnPaJycVRV2cupkfWhH+zbrkaqVQ6KVmX5wQU2rzd+p3fYhGupD9QZJYAegUoY0qjhEb6wCGCGuebFAYEyknwg72rz1jmiGN8mfn1bi3piPihDcGi8/8xP9EM1jKeZPIGyHOPk+OKU5hCoNHajfVWD782o5xOMeX+DjtIG6oZ+WGgJ485QD/BiQ8AeHGqCOhqVBpRbr9pmmL5DAuxk4I8EmypO6xPWJ6qO0++EZE30H4a2awH0DdyUJFPFnhLoijfu9b4oajW8sdLV5uzGDdNYO9Fkp4ju7IBpWQz0PD1Z9VDaHV/la6druJSmQoJQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
